title: Goutham Kumar Vemasani # your name (or website title) here
# logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
    MS Business Analytics, Purdue University
    <br>
    B.E, BITS PILANI, Pilani Campus
    <br>
    <br>
    <a href="https://www.linkedin.com/in/goutham-vemasani-57685773/">Gouthamlinkedin</a> 
    <br>
    <a href="https://github.com/gvemasani/portfolio">vemasanigithub</a> 
    <br>
    <br>
  </p>
